services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Database=TicTacToe;Username=postgres;Password=mypassword123
      - GameSettings__BoardSize=3
      - GameSettings__WinCondition=3
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=TicTacToe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postgres_data: